Feature/next
bildvitta/asteroid-cli pull request #1
Opened 2022-07-21 15:10 UTC by eliasassuncao

2022-07-21 16:06 UTC, gcarpi requested changes

2022-07-21 16:06 UTC, gcarpi commented on src/templates/form.vue.ejs
> +        <!-- TODO: Irá ter esse botão na página de formulário? definir padrão com os designers -->
Acho que pode ser substítuido pelo próprio `qas-actions-menu`. Aqui no Modular usamos em todo Form.

2022-07-21 16:06 UTC, gcarpi commented on src/templates/list.vue.ejs
> +  <qas-list-view v-model:fields="fields" v-model:results="results" class="container spaced" entity="<%= props.name %>">
Não é necessário mais as classes `container spaced`, já são adicionadas por padrão nas `view's`.

2022-07-21 16:06 UTC, gcarpi commented on src/templates/list.vue.ejs
>          <qas-btn hide-mobile-label icon="add" label="Criar nova __MUDAR__NOME__" :to="{ name: '<%= props.createName %>' }" />
Acredito que a propriedade precisa adicionar a prop `padding="md"` por padrão

2022-07-21 16:06 UTC, gcarpi commented on src/templates/form.vue.ejs
> +  <qas-form-view v-model="values" v-model:errors="errors" v-model:fields="fields" class="container spaced" entity="<%= props.name %>" :mode="mx_mode" @submit-success="submitSuccess">
Não é necessário mais as classes `container spaced`, já são adicionadas por padrão nas `view's`.

2022-07-21 16:06 UTC, gcarpi commented on src/templates/single.vue.ejs
> +  <qas-single-view v-model:fields="fields" v-model:result="result" class="container spaced" entity="<%= props.name %>">
Não é necessário mais as classes `container spaced`, já são adicionadas por padrão nas `view's`.

2022-07-21 16:06 UTC, gcarpi commented on src/templates/single.vue.ejs
>          <qas-btn hide-mobile-label icon="o_create" label="Editar __MUDAR__NOME__" :to="{ name: '<%= props.editName %>', params: { id: result.uuid } }" />
Adicionar por padrão a prop `padding="md"`

2022-07-21 16:10 UTC, gcarpi commented
Alguns pontos que senti falta (sei que é só um ponta-pé):

* Possibilidade de passar os field's que serão exibidos nas páginas;
* Criar automaticamente os objetos dos fields e columns com base nesses field's requisitados;
* Auto-importar as rotas e store;

2022-07-25 20:27 UTC, eliasassuncao commented on src/templates/list.vue.ejs
> +  <qas-list-view v-model:fields="fields" v-model:results="results" class="container spaced" entity="<%= props.name %>">
feito

2022-07-25 20:28 UTC, eliasassuncao commented on src/templates/form.vue.ejs
> +  <qas-form-view v-model="values" v-model:errors="errors" v-model:fields="fields" class="container spaced" entity="<%= props.name %>" :mode="mx_mode" @submit-success="submitSuccess">
feito

2022-07-25 20:28 UTC, eliasassuncao commented on src/templates/single.vue.ejs
> +  <qas-single-view v-model:fields="fields" v-model:result="result" class="container spaced" entity="<%= props.name %>">
feito

2022-07-25 20:48 UTC, eliasassuncao commented on src/templates/list.vue.ejs
>          <qas-btn hide-mobile-label icon="add" label="Criar nova __MUDAR__NOME__" :to="{ name: '<%= props.createName %>' }" />
feito

2022-07-25 20:48 UTC, eliasassuncao commented on src/templates/single.vue.ejs
>          <qas-btn hide-mobile-label icon="o_create" label="Editar __MUDAR__NOME__" :to="{ name: '<%= props.editName %>', params: { id: result.uuid } }" />
feito

2022-09-06 12:31 UTC, gcarpi requested changes

2022-09-06 12:31 UTC, gcarpi commented on src/templates/route.js.ejs
> +  }<%_ if(props.result.form !== 'none' || props.result.single){ _%>,<%_ } %>
O que são esses if's vazios? 🤔

2022-09-06 12:31 UTC, gcarpi commented on src/templates/route.js.ejs
> +  }<%_ if(props.result.single){ _%>,<%_ } %>
O que são esses if's vazios? 🤔

2022-09-06 12:31 UTC, gcarpi commented on src/commands/generate.js
> +        choices: ['all', 'create', 'replace', 'not-create'],
Qual é a ideia do `not-create`? Não poderia ser um type `multiselect` que resolveria a questão de selecionar apenas o que queremos?

2022-09-06 12:31 UTC, gcarpi commented on src/templates/list.vue.ejs
>          'title',
Se por enquanto não vamos ter a CLI lidando com os `fields` não seria interessante remover esse `title`?

2022-09-06 12:31 UTC, gcarpi commented on src/templates/list.vue.ejs
>          'title',
Pois nem toda listagem tem um `title`...

2022-09-06 12:33 UTC, eliasassuncao commented on src/templates/list.vue.ejs
>          'title',
feito

2022-09-06 12:35 UTC, eliasassuncao commented on src/commands/generate.js
> +        choices: ['all', 'create', 'replace', 'not-create'],
a ideia seria q eu tenho as possibilidades de:
- criar um form q seja edit e create
- somente o form de create
- somente o form de edit
- e caso nao queira q tenha formulario, pq pode acontecer de eu querer criar somente um list, ou somente um single, etc

2022-09-06 12:52 UTC, eliasassuncao commented on src/templates/route.js.ejs
> +  }<%_ if(props.result.form !== 'none' || props.result.single){ _%>,<%_ } %>
alinhado discord

2022-09-06 12:52 UTC, eliasassuncao commented on src/templates/route.js.ejs
> +  }<%_ if(props.result.single){ _%>,<%_ } %>
alinhado discord

2022-09-06 12:58 UTC, gcarpi approved these changes

2022-09-07 18:42 UTC, DouglasCalora approved these changes

2022-09-07 18:43 UTC, merged